using Test, Braket, BraketSimulator

@testset "IR validation" begin
    sim = DensityMatrixSimulator(2, 0)
    results = [(type="NotARealResult",)]
    @test_throws ErrorException BraketSimulator._validate_ir_results_compatibility(sim, results, Val(:OpenQASM))
    @test_throws ErrorException BraketSimulator._validate_ir_results_compatibility(sim, results, Val(:JAQCD))
    
    @test_throws ErrorException BraketSimulator._validate_input_provided(Circuit([(Rx(FreeParameter(:α)), 0)]))
    @test isnothing(BraketSimulator._validate_input_provided(Circuit([(Rx(0.1), 0)])))

    
    sim = DensityMatrixSimulator(2, 0)
    c = Circuit([(Rx(0.1), 0)])
    @test_logs (:warn, "You are running a noise-free circuit on the density matrix simulator. Consider running this circuit on the state vector simulator: LocalSimulator(\"braket_sv_v2\") for a better user experience.") BraketSimulator._validate_ir_instructions_compatibility(sim, c, Val(:OpenQASM))
    @test_logs (:warn, "You are running a noise-free circuit on the density matrix simulator. Consider running this circuit on the state vector simulator: LocalSimulator(\"braket_sv_v2\") for a better user experience.") BraketSimulator._validate_ir_instructions_compatibility(sim, c, Val(:JAQCD))
    sim = StateVectorSimulator(2, 0)
    c = Circuit([(BitFlip(0.1), 0)])
    @test_throws ValidationError BraketSimulator._validate_ir_instructions_compatibility(sim, c, Val(:OpenQASM))
    @test_throws ValidationError BraketSimulator._validate_ir_instructions_compatibility(sim, c, Val(:JAQCD))

    @testset "Observable compatibility for shots>0 OpenQASM" begin
        @testset "compatible observables" begin
            sim = StateVectorSimulator(2, 0)
            c = Circuit([(H(), 0), (H(), 1)])
            Expectation(c, Braket.Observables.Z() * Braket.Observables.X(), [0, 1])
            Variance(c, Braket.Observables.Y(), 0)
            @test_throws ValidationError BraketSimulator._verify_openqasm_shots_observables(c)
            c = Circuit([(H(), 0), (H(), 1)])
            Expectation(c, Braket.Observables.Z() * Braket.Observables.X(), [0, 1])
            Variance(c, Braket.Observables.Z(), 0)
            @test isnothing(BraketSimulator._verify_openqasm_shots_observables(c))
        end
        @testset "full PennyLane example" begin 
            # from a PennyLane VQE workload -- good example of a lot of
            # compatible observables!
            n_params = 146
            inputs = Dict("p_$pix"=>0.0 for pix in 0:n_params-1)
            source = """
            OPENQASM 3.0;
            input float p_0;
            input float p_31;
            input float p_117;
            input float p_52;
            input float p_103;
            input float p_87;
            input float p_46;
            input float p_34;
            input float p_49;
            input float p_75;
            input float p_35;
            input float p_123;
            input float p_1;
            input float p_15;
            input float p_73;
            input float p_25;
            input float p_93;
            input float p_116;
            input float p_13;
            input float p_86;
            input float p_23;
            input float p_4;
            input float p_32;
            input float p_107;
            input float p_119;
            input float p_63;
            input float p_89;
            input float p_5;
            input float p_111;
            input float p_127;
            input float p_77;
            input float p_53;
            input float p_97;
            input float p_137;
            input float p_48;
            input float p_114;
            input float p_17;
            input float p_42;
            input float p_40;
            input float p_67;
            input float p_126;
            input float p_118;
            input float p_96;
            input float p_112;
            input float p_136;
            input float p_88;
            input float p_33;
            input float p_57;
            input float p_82;
            input float p_110;
            input float p_129;
            input float p_41;
            input float p_80;
            input float p_99;
            input float p_139;
            input float p_66;
            input float p_44;
            input float p_121;
            input float p_69;
            input float p_91;
            input float p_131;
            input float p_3;
            input float p_140;
            input float p_45;
            input float p_81;
            input float p_108;
            input float p_94;
            input float p_134;
            input float p_37;
            input float p_61;
            input float p_100;
            input float p_106;
            input float p_27;
            input float p_84;
            input float p_109;
            input float p_115;
            input float p_141;
            input float p_128;
            input float p_85;
            input float p_122;
            input float p_78;
            input float p_98;
            input float p_138;
            input float p_120;
            input float p_92;
            input float p_7;
            input float p_132;
            input float p_144;
            input float p_18;
            input float p_76;
            input float p_90;
            input float p_101;
            input float p_130;
            input float p_36;
            input float p_16;
            input float p_68;
            input float p_26;
            input float p_145;
            input float p_79;
            input float p_62;
            input float p_104;
            input float p_60;
            input float p_19;
            input float p_29;
            input float p_105;
            input float p_142;
            input float p_71;
            input float p_6;
            input float p_58;
            input float p_124;
            input float p_11;
            input float p_21;
            input float p_50;
            input float p_56;
            input float p_9;
            input float p_74;
            input float p_43;
            input float p_102;
            input float p_125;
            input float p_14;
            input float p_59;
            input float p_24;
            input float p_95;
            input float p_135;
            input float p_64;
            input float p_133;
            input float p_113;
            input float p_51;
            input float p_65;
            input float p_38;
            input float p_72;
            input float p_83;
            input float p_70;
            input float p_28;
            input float p_12;
            input float p_30;
            input float p_22;
            input float p_47;
            input float p_54;
            input float p_10;
            input float p_20;
            input float p_39;
            input float p_55;
            input float p_143;
            input float p_8;
            input float p_2;
            qubit[8] q;
            x q[0];
            x q[1];
            x q[2];
            x q[3];
            cnot q[4], q[5];
            cnot q[0], q[4];
            h q[5];
            h q[0];
            cnot q[4], q[5];
            cnot q[0], q[1];
            ry(p_0) q[1];
            ry(p_1) q[0];
            cnot q[0], q[5];
            h q[5];
            cnot q[5], q[1];
            ry(p_2) q[1];
            ry(p_3) q[0];
            cnot q[4], q[1];
            cnot q[4], q[0];
            ry(p_4) q[1];
            ry(p_5) q[0];
            cnot q[5], q[1];
            h q[5];
            cnot q[0], q[5];
            ry(p_6) q[1];
            ry(p_7) q[0];
            cnot q[0], q[1];
            cnot q[4], q[0];
            h q[0];
            h q[5];
            cnot q[0], q[4];
            cnot q[4], q[5];
            cnot q[4], q[7];
            cnot q[0], q[4];
            h q[7];
            h q[0];
            cnot q[4], q[7];
            cnot q[0], q[1];
            ry(p_8) q[1];
            ry(p_9) q[0];
            cnot q[0], q[7];
            h q[7];
            cnot q[7], q[1];
            ry(p_10) q[1];
            ry(p_11) q[0];
            cnot q[4], q[1];
            cnot q[4], q[0];
            ry(p_12) q[1];
            ry(p_13) q[0];
            cnot q[7], q[1];
            h q[7];
            cnot q[0], q[7];
            ry(p_14) q[1];
            ry(p_15) q[0];
            cnot q[0], q[1];
            cnot q[4], q[0];
            h q[0];
            h q[7];
            cnot q[0], q[4];
            cnot q[4], q[7];
            cnot q[5], q[6];
            cnot q[0], q[5];
            h q[6];
            h q[0];
            cnot q[5], q[6];
            cnot q[0], q[1];
            ry(p_16) q[1];
            ry(p_17) q[0];
            cnot q[0], q[6];
            h q[6];
            cnot q[6], q[1];
            ry(p_18) q[1];
            ry(p_19) q[0];
            cnot q[5], q[1];
            cnot q[5], q[0];
            ry(p_20) q[1];
            ry(p_21) q[0];
            cnot q[6], q[1];
            h q[6];
            cnot q[0], q[6];
            ry(p_22) q[1];
            ry(p_23) q[0];
            cnot q[0], q[1];
            cnot q[5], q[0];
            h q[0];
            h q[6];
            cnot q[0], q[5];
            cnot q[5], q[6];
            cnot q[6], q[7];
            cnot q[0], q[6];
            h q[7];
            h q[0];
            cnot q[6], q[7];
            cnot q[0], q[1];
            ry(p_24) q[1];
            ry(p_25) q[0];
            cnot q[0], q[7];
            h q[7];
            cnot q[7], q[1];
            ry(p_26) q[1];
            ry(p_27) q[0];
            cnot q[6], q[1];
            cnot q[6], q[0];
            ry(p_28) q[1];
            ry(p_29) q[0];
            cnot q[7], q[1];
            h q[7];
            cnot q[0], q[7];
            ry(p_30) q[1];
            ry(p_31) q[0];
            cnot q[0], q[1];
            cnot q[6], q[0];
            h q[0];
            h q[7];
            cnot q[0], q[6];
            cnot q[6], q[7];
            cnot q[4], q[6];
            cnot q[0], q[4];
            h q[6];
            h q[0];
            cnot q[4], q[6];
            cnot q[0], q[2];
            ry(p_32) q[2];
            ry(p_33) q[0];
            cnot q[0], q[6];
            h q[6];
            cnot q[6], q[2];
            ry(p_34) q[2];
            ry(p_35) q[0];
            cnot q[4], q[2];
            cnot q[4], q[0];
            ry(p_36) q[2];
            ry(p_37) q[0];
            cnot q[6], q[2];
            h q[6];
            cnot q[0], q[6];
            ry(p_38) q[2];
            ry(p_39) q[0];
            cnot q[0], q[2];
            cnot q[4], q[0];
            h q[0];
            h q[6];
            cnot q[0], q[4];
            cnot q[4], q[6];
            cnot q[4], q[5];
            cnot q[0], q[4];
            h q[5];
            h q[0];
            cnot q[4], q[5];
            cnot q[0], q[3];
            ry(p_40) q[3];
            ry(p_41) q[0];
            cnot q[0], q[5];
            h q[5];
            cnot q[5], q[3];
            ry(p_42) q[3];
            ry(p_43) q[0];
            cnot q[4], q[3];
            cnot q[4], q[0];
            ry(p_44) q[3];
            ry(p_45) q[0];
            cnot q[5], q[3];
            h q[5];
            cnot q[0], q[5];
            ry(p_46) q[3];
            ry(p_47) q[0];
            cnot q[0], q[3];
            cnot q[4], q[0];
            h q[0];
            h q[5];
            cnot q[0], q[4];
            cnot q[4], q[5];
            cnot q[4], q[7];
            cnot q[0], q[4];
            h q[7];
            h q[0];
            cnot q[4], q[7];
            cnot q[0], q[3];
            ry(p_48) q[3];
            ry(p_49) q[0];
            cnot q[0], q[7];
            h q[7];
            cnot q[7], q[3];
            ry(p_50) q[3];
            ry(p_51) q[0];
            cnot q[4], q[3];
            cnot q[4], q[0];
            ry(p_52) q[3];
            ry(p_53) q[0];
            cnot q[7], q[3];
            h q[7];
            cnot q[0], q[7];
            ry(p_54) q[3];
            ry(p_55) q[0];
            cnot q[0], q[3];
            cnot q[4], q[0];
            h q[0];
            h q[7];
            cnot q[0], q[4];
            cnot q[4], q[7];
            cnot q[5], q[6];
            cnot q[0], q[5];
            h q[6];
            h q[0];
            cnot q[5], q[6];
            cnot q[0], q[3];
            ry(p_56) q[3];
            ry(p_57) q[0];
            cnot q[0], q[6];
            h q[6];
            cnot q[6], q[3];
            ry(p_58) q[3];
            ry(p_59) q[0];
            cnot q[5], q[3];
            cnot q[5], q[0];
            ry(p_60) q[3];
            ry(p_61) q[0];
            cnot q[6], q[3];
            h q[6];
            cnot q[0], q[6];
            ry(p_62) q[3];
            ry(p_63) q[0];
            cnot q[0], q[3];
            cnot q[5], q[0];
            h q[0];
            h q[6];
            cnot q[0], q[5];
            cnot q[5], q[6];
            cnot q[6], q[7];
            cnot q[0], q[6];
            h q[7];
            h q[0];
            cnot q[6], q[7];
            cnot q[0], q[3];
            ry(p_64) q[3];
            ry(p_65) q[0];
            cnot q[0], q[7];
            h q[7];
            cnot q[7], q[3];
            ry(p_66) q[3];
            ry(p_67) q[0];
            cnot q[6], q[3];
            cnot q[6], q[0];
            ry(p_68) q[3];
            ry(p_69) q[0];
            cnot q[7], q[3];
            h q[7];
            cnot q[0], q[7];
            ry(p_70) q[3];
            ry(p_71) q[0];
            cnot q[0], q[3];
            cnot q[6], q[0];
            h q[0];
            h q[7];
            cnot q[0], q[6];
            cnot q[6], q[7];
            cnot q[4], q[5];
            cnot q[1], q[4];
            h q[5];
            h q[1];
            cnot q[4], q[5];
            cnot q[1], q[2];
            ry(p_72) q[2];
            ry(p_73) q[1];
            cnot q[1], q[5];
            h q[5];
            cnot q[5], q[2];
            ry(p_74) q[2];
            ry(p_75) q[1];
            cnot q[4], q[2];
            cnot q[4], q[1];
            ry(p_76) q[2];
            ry(p_77) q[1];
            cnot q[5], q[2];
            h q[5];
            cnot q[1], q[5];
            ry(p_78) q[2];
            ry(p_79) q[1];
            cnot q[1], q[2];
            cnot q[4], q[1];
            h q[1];
            h q[5];
            cnot q[1], q[4];
            cnot q[4], q[5];
            cnot q[4], q[7];
            cnot q[1], q[4];
            h q[7];
            h q[1];
            cnot q[4], q[7];
            cnot q[1], q[2];
            ry(p_80) q[2];
            ry(p_81) q[1];
            cnot q[1], q[7];
            h q[7];
            cnot q[7], q[2];
            ry(p_82) q[2];
            ry(p_83) q[1];
            cnot q[4], q[2];
            cnot q[4], q[1];
            ry(p_84) q[2];
            ry(p_85) q[1];
            cnot q[7], q[2];
            h q[7];
            cnot q[1], q[7];
            ry(p_86) q[2];
            ry(p_87) q[1];
            cnot q[1], q[2];
            cnot q[4], q[1];
            h q[1];
            h q[7];
            cnot q[1], q[4];
            cnot q[4], q[7];
            cnot q[5], q[6];
            cnot q[1], q[5];
            h q[6];
            h q[1];
            cnot q[5], q[6];
            cnot q[1], q[2];
            ry(p_88) q[2];
            ry(p_89) q[1];
            cnot q[1], q[6];
            h q[6];
            cnot q[6], q[2];
            ry(p_90) q[2];
            ry(p_91) q[1];
            cnot q[5], q[2];
            cnot q[5], q[1];
            ry(p_92) q[2];
            ry(p_93) q[1];
            cnot q[6], q[2];
            h q[6];
            cnot q[1], q[6];
            ry(p_94) q[2];
            ry(p_95) q[1];
            cnot q[1], q[2];
            cnot q[5], q[1];
            h q[1];
            h q[6];
            cnot q[1], q[5];
            cnot q[5], q[6];
            cnot q[6], q[7];
            cnot q[1], q[6];
            h q[7];
            h q[1];
            cnot q[6], q[7];
            cnot q[1], q[2];
            ry(p_96) q[2];
            ry(p_97) q[1];
            cnot q[1], q[7];
            h q[7];
            cnot q[7], q[2];
            ry(p_98) q[2];
            ry(p_99) q[1];
            cnot q[6], q[2];
            cnot q[6], q[1];
            ry(p_100) q[2];
            ry(p_101) q[1];
            cnot q[7], q[2];
            h q[7];
            cnot q[1], q[7];
            ry(p_102) q[2];
            ry(p_103) q[1];
            cnot q[1], q[2];
            cnot q[6], q[1];
            h q[1];
            h q[7];
            cnot q[1], q[6];
            cnot q[6], q[7];
            cnot q[5], q[7];
            cnot q[1], q[5];
            h q[7];
            h q[1];
            cnot q[5], q[7];
            cnot q[1], q[3];
            ry(p_104) q[3];
            ry(p_105) q[1];
            cnot q[1], q[7];
            h q[7];
            cnot q[7], q[3];
            ry(p_106) q[3];
            ry(p_107) q[1];
            cnot q[5], q[3];
            cnot q[5], q[1];
            ry(p_108) q[3];
            ry(p_109) q[1];
            cnot q[7], q[3];
            h q[7];
            cnot q[1], q[7];
            ry(p_110) q[3];
            ry(p_111) q[1];
            cnot q[1], q[3];
            cnot q[5], q[1];
            h q[1];
            h q[7];
            cnot q[1], q[5];
            cnot q[5], q[7];
            cnot q[4], q[5];
            cnot q[2], q[4];
            h q[5];
            h q[2];
            cnot q[4], q[5];
            cnot q[2], q[3];
            ry(p_112) q[3];
            ry(p_113) q[2];
            cnot q[2], q[5];
            h q[5];
            cnot q[5], q[3];
            ry(p_114) q[3];
            ry(p_115) q[2];
            cnot q[4], q[3];
            cnot q[4], q[2];
            ry(p_116) q[3];
            ry(p_117) q[2];
            cnot q[5], q[3];
            h q[5];
            cnot q[2], q[5];
            ry(p_118) q[3];
            ry(p_119) q[2];
            cnot q[2], q[3];
            cnot q[4], q[2];
            h q[2];
            h q[5];
            cnot q[2], q[4];
            cnot q[4], q[5];
            cnot q[4], q[7];
            cnot q[2], q[4];
            h q[7];
            h q[2];
            cnot q[4], q[7];
            cnot q[2], q[3];
            ry(p_120) q[3];
            ry(p_121) q[2];
            cnot q[2], q[7];
            h q[7];
            cnot q[7], q[3];
            ry(p_122) q[3];
            ry(p_123) q[2];
            cnot q[4], q[3];
            cnot q[4], q[2];
            ry(p_124) q[3];
            ry(p_125) q[2];
            cnot q[7], q[3];
            h q[7];
            cnot q[2], q[7];
            ry(p_126) q[3];
            ry(p_127) q[2];
            cnot q[2], q[3];
            cnot q[4], q[2];
            h q[2];
            h q[7];
            cnot q[2], q[4];
            cnot q[4], q[7];
            cnot q[5], q[6];
            cnot q[2], q[5];
            h q[6];
            h q[2];
            cnot q[5], q[6];
            cnot q[2], q[3];
            ry(p_128) q[3];
            ry(p_129) q[2];
            cnot q[2], q[6];
            h q[6];
            cnot q[6], q[3];
            ry(p_130) q[3];
            ry(p_131) q[2];
            cnot q[5], q[3];
            cnot q[5], q[2];
            ry(p_132) q[3];
            ry(p_133) q[2];
            cnot q[6], q[3];
            h q[6];
            cnot q[2], q[6];
            ry(p_134) q[3];
            ry(p_135) q[2];
            cnot q[2], q[3];
            cnot q[5], q[2];
            h q[2];
            h q[6];
            cnot q[2], q[5];
            cnot q[5], q[6];
            cnot q[6], q[7];
            cnot q[2], q[6];
            h q[7];
            h q[2];
            cnot q[6], q[7];
            cnot q[2], q[3];
            ry(p_136) q[3];
            ry(p_137) q[2];
            cnot q[2], q[7];
            h q[7];
            cnot q[7], q[3];
            ry(p_138) q[3];
            ry(p_139) q[2];
            cnot q[6], q[3];
            cnot q[6], q[2];
            ry(p_140) q[3];
            ry(p_141) q[2];
            cnot q[7], q[3];
            h q[7];
            cnot q[2], q[7];
            ry(p_142) q[3];
            ry(p_143) q[2];
            cnot q[2], q[3];
            cnot q[6], q[2];
            h q[2];
            h q[7];
            cnot q[2], q[6];
            cnot q[6], q[7];
            ry(p_144) q[3];
            ry(p_145) q[7];
            #pragma braket result expectation z(q[3]) @ z(q[5]) @ z(q[6]) @ z(q[7])
            #pragma braket result expectation z(q[1]) @ z(q[3]) @ z(q[4]) @ z(q[5]) @ z(q[6]) @ z(q[7])
            #pragma braket result expectation z(q[2]) @ z(q[3]) @ z(q[4]) @ z(q[5]) @ z(q[6]) @ z(q[7])
            #pragma braket result expectation z(q[3]) @ z(q[4]) @ z(q[5]) @ z(q[6]) @ z(q[7])
            #pragma braket result expectation z(q[0]) @ z(q[3]) @ z(q[4]) @ z(q[5]) @ z(q[6]) @ z(q[7])
            """
            circ = Circuit(source, inputs)
            @test isnothing(BraketSimulator._verify_openqasm_shots_observables(circ))
            # differs from source above by change of one Z to X in observables list
            bad_source = """
            OPENQASM 3.0;
            input float p_0;
            input float p_31;
            input float p_117;
            input float p_52;
            input float p_103;
            input float p_87;
            input float p_46;
            input float p_34;
            input float p_49;
            input float p_75;
            input float p_35;
            input float p_123;
            input float p_1;
            input float p_15;
            input float p_73;
            input float p_25;
            input float p_93;
            input float p_116;
            input float p_13;
            input float p_86;
            input float p_23;
            input float p_4;
            input float p_32;
            input float p_107;
            input float p_119;
            input float p_63;
            input float p_89;
            input float p_5;
            input float p_111;
            input float p_127;
            input float p_77;
            input float p_53;
            input float p_97;
            input float p_137;
            input float p_48;
            input float p_114;
            input float p_17;
            input float p_42;
            input float p_40;
            input float p_67;
            input float p_126;
            input float p_118;
            input float p_96;
            input float p_112;
            input float p_136;
            input float p_88;
            input float p_33;
            input float p_57;
            input float p_82;
            input float p_110;
            input float p_129;
            input float p_41;
            input float p_80;
            input float p_99;
            input float p_139;
            input float p_66;
            input float p_44;
            input float p_121;
            input float p_69;
            input float p_91;
            input float p_131;
            input float p_3;
            input float p_140;
            input float p_45;
            input float p_81;
            input float p_108;
            input float p_94;
            input float p_134;
            input float p_37;
            input float p_61;
            input float p_100;
            input float p_106;
            input float p_27;
            input float p_84;
            input float p_109;
            input float p_115;
            input float p_141;
            input float p_128;
            input float p_85;
            input float p_122;
            input float p_78;
            input float p_98;
            input float p_138;
            input float p_120;
            input float p_92;
            input float p_7;
            input float p_132;
            input float p_144;
            input float p_18;
            input float p_76;
            input float p_90;
            input float p_101;
            input float p_130;
            input float p_36;
            input float p_16;
            input float p_68;
            input float p_26;
            input float p_145;
            input float p_79;
            input float p_62;
            input float p_104;
            input float p_60;
            input float p_19;
            input float p_29;
            input float p_105;
            input float p_142;
            input float p_71;
            input float p_6;
            input float p_58;
            input float p_124;
            input float p_11;
            input float p_21;
            input float p_50;
            input float p_56;
            input float p_9;
            input float p_74;
            input float p_43;
            input float p_102;
            input float p_125;
            input float p_14;
            input float p_59;
            input float p_24;
            input float p_95;
            input float p_135;
            input float p_64;
            input float p_133;
            input float p_113;
            input float p_51;
            input float p_65;
            input float p_38;
            input float p_72;
            input float p_83;
            input float p_70;
            input float p_28;
            input float p_12;
            input float p_30;
            input float p_22;
            input float p_47;
            input float p_54;
            input float p_10;
            input float p_20;
            input float p_39;
            input float p_55;
            input float p_143;
            input float p_8;
            input float p_2;
            qubit[8] q;
            x q[0];
            x q[1];
            x q[2];
            x q[3];
            cnot q[4], q[5];
            cnot q[0], q[4];
            h q[5];
            h q[0];
            cnot q[4], q[5];
            cnot q[0], q[1];
            ry(p_0) q[1];
            ry(p_1) q[0];
            cnot q[0], q[5];
            h q[5];
            cnot q[5], q[1];
            ry(p_2) q[1];
            ry(p_3) q[0];
            cnot q[4], q[1];
            cnot q[4], q[0];
            ry(p_4) q[1];
            ry(p_5) q[0];
            cnot q[5], q[1];
            h q[5];
            cnot q[0], q[5];
            ry(p_6) q[1];
            ry(p_7) q[0];
            cnot q[0], q[1];
            cnot q[4], q[0];
            h q[0];
            h q[5];
            cnot q[0], q[4];
            cnot q[4], q[5];
            cnot q[4], q[7];
            cnot q[0], q[4];
            h q[7];
            h q[0];
            cnot q[4], q[7];
            cnot q[0], q[1];
            ry(p_8) q[1];
            ry(p_9) q[0];
            cnot q[0], q[7];
            h q[7];
            cnot q[7], q[1];
            ry(p_10) q[1];
            ry(p_11) q[0];
            cnot q[4], q[1];
            cnot q[4], q[0];
            ry(p_12) q[1];
            ry(p_13) q[0];
            cnot q[7], q[1];
            h q[7];
            cnot q[0], q[7];
            ry(p_14) q[1];
            ry(p_15) q[0];
            cnot q[0], q[1];
            cnot q[4], q[0];
            h q[0];
            h q[7];
            cnot q[0], q[4];
            cnot q[4], q[7];
            cnot q[5], q[6];
            cnot q[0], q[5];
            h q[6];
            h q[0];
            cnot q[5], q[6];
            cnot q[0], q[1];
            ry(p_16) q[1];
            ry(p_17) q[0];
            cnot q[0], q[6];
            h q[6];
            cnot q[6], q[1];
            ry(p_18) q[1];
            ry(p_19) q[0];
            cnot q[5], q[1];
            cnot q[5], q[0];
            ry(p_20) q[1];
            ry(p_21) q[0];
            cnot q[6], q[1];
            h q[6];
            cnot q[0], q[6];
            ry(p_22) q[1];
            ry(p_23) q[0];
            cnot q[0], q[1];
            cnot q[5], q[0];
            h q[0];
            h q[6];
            cnot q[0], q[5];
            cnot q[5], q[6];
            cnot q[6], q[7];
            cnot q[0], q[6];
            h q[7];
            h q[0];
            cnot q[6], q[7];
            cnot q[0], q[1];
            ry(p_24) q[1];
            ry(p_25) q[0];
            cnot q[0], q[7];
            h q[7];
            cnot q[7], q[1];
            ry(p_26) q[1];
            ry(p_27) q[0];
            cnot q[6], q[1];
            cnot q[6], q[0];
            ry(p_28) q[1];
            ry(p_29) q[0];
            cnot q[7], q[1];
            h q[7];
            cnot q[0], q[7];
            ry(p_30) q[1];
            ry(p_31) q[0];
            cnot q[0], q[1];
            cnot q[6], q[0];
            h q[0];
            h q[7];
            cnot q[0], q[6];
            cnot q[6], q[7];
            cnot q[4], q[6];
            cnot q[0], q[4];
            h q[6];
            h q[0];
            cnot q[4], q[6];
            cnot q[0], q[2];
            ry(p_32) q[2];
            ry(p_33) q[0];
            cnot q[0], q[6];
            h q[6];
            cnot q[6], q[2];
            ry(p_34) q[2];
            ry(p_35) q[0];
            cnot q[4], q[2];
            cnot q[4], q[0];
            ry(p_36) q[2];
            ry(p_37) q[0];
            cnot q[6], q[2];
            h q[6];
            cnot q[0], q[6];
            ry(p_38) q[2];
            ry(p_39) q[0];
            cnot q[0], q[2];
            cnot q[4], q[0];
            h q[0];
            h q[6];
            cnot q[0], q[4];
            cnot q[4], q[6];
            cnot q[4], q[5];
            cnot q[0], q[4];
            h q[5];
            h q[0];
            cnot q[4], q[5];
            cnot q[0], q[3];
            ry(p_40) q[3];
            ry(p_41) q[0];
            cnot q[0], q[5];
            h q[5];
            cnot q[5], q[3];
            ry(p_42) q[3];
            ry(p_43) q[0];
            cnot q[4], q[3];
            cnot q[4], q[0];
            ry(p_44) q[3];
            ry(p_45) q[0];
            cnot q[5], q[3];
            h q[5];
            cnot q[0], q[5];
            ry(p_46) q[3];
            ry(p_47) q[0];
            cnot q[0], q[3];
            cnot q[4], q[0];
            h q[0];
            h q[5];
            cnot q[0], q[4];
            cnot q[4], q[5];
            cnot q[4], q[7];
            cnot q[0], q[4];
            h q[7];
            h q[0];
            cnot q[4], q[7];
            cnot q[0], q[3];
            ry(p_48) q[3];
            ry(p_49) q[0];
            cnot q[0], q[7];
            h q[7];
            cnot q[7], q[3];
            ry(p_50) q[3];
            ry(p_51) q[0];
            cnot q[4], q[3];
            cnot q[4], q[0];
            ry(p_52) q[3];
            ry(p_53) q[0];
            cnot q[7], q[3];
            h q[7];
            cnot q[0], q[7];
            ry(p_54) q[3];
            ry(p_55) q[0];
            cnot q[0], q[3];
            cnot q[4], q[0];
            h q[0];
            h q[7];
            cnot q[0], q[4];
            cnot q[4], q[7];
            cnot q[5], q[6];
            cnot q[0], q[5];
            h q[6];
            h q[0];
            cnot q[5], q[6];
            cnot q[0], q[3];
            ry(p_56) q[3];
            ry(p_57) q[0];
            cnot q[0], q[6];
            h q[6];
            cnot q[6], q[3];
            ry(p_58) q[3];
            ry(p_59) q[0];
            cnot q[5], q[3];
            cnot q[5], q[0];
            ry(p_60) q[3];
            ry(p_61) q[0];
            cnot q[6], q[3];
            h q[6];
            cnot q[0], q[6];
            ry(p_62) q[3];
            ry(p_63) q[0];
            cnot q[0], q[3];
            cnot q[5], q[0];
            h q[0];
            h q[6];
            cnot q[0], q[5];
            cnot q[5], q[6];
            cnot q[6], q[7];
            cnot q[0], q[6];
            h q[7];
            h q[0];
            cnot q[6], q[7];
            cnot q[0], q[3];
            ry(p_64) q[3];
            ry(p_65) q[0];
            cnot q[0], q[7];
            h q[7];
            cnot q[7], q[3];
            ry(p_66) q[3];
            ry(p_67) q[0];
            cnot q[6], q[3];
            cnot q[6], q[0];
            ry(p_68) q[3];
            ry(p_69) q[0];
            cnot q[7], q[3];
            h q[7];
            cnot q[0], q[7];
            ry(p_70) q[3];
            ry(p_71) q[0];
            cnot q[0], q[3];
            cnot q[6], q[0];
            h q[0];
            h q[7];
            cnot q[0], q[6];
            cnot q[6], q[7];
            cnot q[4], q[5];
            cnot q[1], q[4];
            h q[5];
            h q[1];
            cnot q[4], q[5];
            cnot q[1], q[2];
            ry(p_72) q[2];
            ry(p_73) q[1];
            cnot q[1], q[5];
            h q[5];
            cnot q[5], q[2];
            ry(p_74) q[2];
            ry(p_75) q[1];
            cnot q[4], q[2];
            cnot q[4], q[1];
            ry(p_76) q[2];
            ry(p_77) q[1];
            cnot q[5], q[2];
            h q[5];
            cnot q[1], q[5];
            ry(p_78) q[2];
            ry(p_79) q[1];
            cnot q[1], q[2];
            cnot q[4], q[1];
            h q[1];
            h q[5];
            cnot q[1], q[4];
            cnot q[4], q[5];
            cnot q[4], q[7];
            cnot q[1], q[4];
            h q[7];
            h q[1];
            cnot q[4], q[7];
            cnot q[1], q[2];
            ry(p_80) q[2];
            ry(p_81) q[1];
            cnot q[1], q[7];
            h q[7];
            cnot q[7], q[2];
            ry(p_82) q[2];
            ry(p_83) q[1];
            cnot q[4], q[2];
            cnot q[4], q[1];
            ry(p_84) q[2];
            ry(p_85) q[1];
            cnot q[7], q[2];
            h q[7];
            cnot q[1], q[7];
            ry(p_86) q[2];
            ry(p_87) q[1];
            cnot q[1], q[2];
            cnot q[4], q[1];
            h q[1];
            h q[7];
            cnot q[1], q[4];
            cnot q[4], q[7];
            cnot q[5], q[6];
            cnot q[1], q[5];
            h q[6];
            h q[1];
            cnot q[5], q[6];
            cnot q[1], q[2];
            ry(p_88) q[2];
            ry(p_89) q[1];
            cnot q[1], q[6];
            h q[6];
            cnot q[6], q[2];
            ry(p_90) q[2];
            ry(p_91) q[1];
            cnot q[5], q[2];
            cnot q[5], q[1];
            ry(p_92) q[2];
            ry(p_93) q[1];
            cnot q[6], q[2];
            h q[6];
            cnot q[1], q[6];
            ry(p_94) q[2];
            ry(p_95) q[1];
            cnot q[1], q[2];
            cnot q[5], q[1];
            h q[1];
            h q[6];
            cnot q[1], q[5];
            cnot q[5], q[6];
            cnot q[6], q[7];
            cnot q[1], q[6];
            h q[7];
            h q[1];
            cnot q[6], q[7];
            cnot q[1], q[2];
            ry(p_96) q[2];
            ry(p_97) q[1];
            cnot q[1], q[7];
            h q[7];
            cnot q[7], q[2];
            ry(p_98) q[2];
            ry(p_99) q[1];
            cnot q[6], q[2];
            cnot q[6], q[1];
            ry(p_100) q[2];
            ry(p_101) q[1];
            cnot q[7], q[2];
            h q[7];
            cnot q[1], q[7];
            ry(p_102) q[2];
            ry(p_103) q[1];
            cnot q[1], q[2];
            cnot q[6], q[1];
            h q[1];
            h q[7];
            cnot q[1], q[6];
            cnot q[6], q[7];
            cnot q[5], q[7];
            cnot q[1], q[5];
            h q[7];
            h q[1];
            cnot q[5], q[7];
            cnot q[1], q[3];
            ry(p_104) q[3];
            ry(p_105) q[1];
            cnot q[1], q[7];
            h q[7];
            cnot q[7], q[3];
            ry(p_106) q[3];
            ry(p_107) q[1];
            cnot q[5], q[3];
            cnot q[5], q[1];
            ry(p_108) q[3];
            ry(p_109) q[1];
            cnot q[7], q[3];
            h q[7];
            cnot q[1], q[7];
            ry(p_110) q[3];
            ry(p_111) q[1];
            cnot q[1], q[3];
            cnot q[5], q[1];
            h q[1];
            h q[7];
            cnot q[1], q[5];
            cnot q[5], q[7];
            cnot q[4], q[5];
            cnot q[2], q[4];
            h q[5];
            h q[2];
            cnot q[4], q[5];
            cnot q[2], q[3];
            ry(p_112) q[3];
            ry(p_113) q[2];
            cnot q[2], q[5];
            h q[5];
            cnot q[5], q[3];
            ry(p_114) q[3];
            ry(p_115) q[2];
            cnot q[4], q[3];
            cnot q[4], q[2];
            ry(p_116) q[3];
            ry(p_117) q[2];
            cnot q[5], q[3];
            h q[5];
            cnot q[2], q[5];
            ry(p_118) q[3];
            ry(p_119) q[2];
            cnot q[2], q[3];
            cnot q[4], q[2];
            h q[2];
            h q[5];
            cnot q[2], q[4];
            cnot q[4], q[5];
            cnot q[4], q[7];
            cnot q[2], q[4];
            h q[7];
            h q[2];
            cnot q[4], q[7];
            cnot q[2], q[3];
            ry(p_120) q[3];
            ry(p_121) q[2];
            cnot q[2], q[7];
            h q[7];
            cnot q[7], q[3];
            ry(p_122) q[3];
            ry(p_123) q[2];
            cnot q[4], q[3];
            cnot q[4], q[2];
            ry(p_124) q[3];
            ry(p_125) q[2];
            cnot q[7], q[3];
            h q[7];
            cnot q[2], q[7];
            ry(p_126) q[3];
            ry(p_127) q[2];
            cnot q[2], q[3];
            cnot q[4], q[2];
            h q[2];
            h q[7];
            cnot q[2], q[4];
            cnot q[4], q[7];
            cnot q[5], q[6];
            cnot q[2], q[5];
            h q[6];
            h q[2];
            cnot q[5], q[6];
            cnot q[2], q[3];
            ry(p_128) q[3];
            ry(p_129) q[2];
            cnot q[2], q[6];
            h q[6];
            cnot q[6], q[3];
            ry(p_130) q[3];
            ry(p_131) q[2];
            cnot q[5], q[3];
            cnot q[5], q[2];
            ry(p_132) q[3];
            ry(p_133) q[2];
            cnot q[6], q[3];
            h q[6];
            cnot q[2], q[6];
            ry(p_134) q[3];
            ry(p_135) q[2];
            cnot q[2], q[3];
            cnot q[5], q[2];
            h q[2];
            h q[6];
            cnot q[2], q[5];
            cnot q[5], q[6];
            cnot q[6], q[7];
            cnot q[2], q[6];
            h q[7];
            h q[2];
            cnot q[6], q[7];
            cnot q[2], q[3];
            ry(p_136) q[3];
            ry(p_137) q[2];
            cnot q[2], q[7];
            h q[7];
            cnot q[7], q[3];
            ry(p_138) q[3];
            ry(p_139) q[2];
            cnot q[6], q[3];
            cnot q[6], q[2];
            ry(p_140) q[3];
            ry(p_141) q[2];
            cnot q[7], q[3];
            h q[7];
            cnot q[2], q[7];
            ry(p_142) q[3];
            ry(p_143) q[2];
            cnot q[2], q[3];
            cnot q[6], q[2];
            h q[2];
            h q[7];
            cnot q[2], q[6];
            cnot q[6], q[7];
            ry(p_144) q[3];
            ry(p_145) q[7];
            #pragma braket result expectation z(q[3]) @ z(q[5]) @ z(q[6]) @ z(q[7])
            #pragma braket result expectation z(q[1]) @ z(q[3]) @ z(q[4]) @ z(q[5]) @ z(q[6]) @ z(q[7])
            #pragma braket result expectation z(q[2]) @ z(q[3]) @ z(q[4]) @ z(q[5]) @ z(q[6]) @ z(q[7])
            #pragma braket result expectation z(q[3]) @ z(q[4]) @ z(q[5]) @ z(q[6]) @ z(q[7])
            #pragma braket result expectation z(q[0]) @ z(q[3]) @ z(q[4]) @ z(q[5]) @ x(q[6]) @ z(q[7])
            """
            circ = Circuit(bad_source, inputs)
            @test_throws ValidationError BraketSimulator._verify_openqasm_shots_observables(circ)
        end
    end
end
