channels = ["conda-forge"]

[deps]
# Conda package names and versions
python = ">=3.9,<4"
amazon-braket-sdk = ">=1.76"
amazon-braket-schemas = ">=1.21"
amazon-braket-default-simulator = ">=1.21"
sympy = ">=1.12"
